apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-services-app
  namespace: price
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-services-app
  template:
    metadata:
      labels:
        app: price-services-app
    spec:
      containers:
      - name: price-services-app
        image: mmregistry.mmvietnam.com:5000/price-services:0.0.1_23
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: mmregistry-secret
