apiVersion: v1
kind: Service
metadata:
  name: price-services
  namespace: price  # namespace the same deployement
spec:
  selector:
    app: price-services-app  #  Pod choose Deployment label
  ports:
    - protocol: TCP
      port: 80           # Port extenal
      targetPort: 80    # Port in container
  type: LoadBalancer     # LoadBalancer provide IP address
